version: '3.8'

services:
  # SagaOS Frontend
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - API_BASE_URL=http://localhost:3001/api
      - WS_URL=ws://localhost:3001/ws
      - APP_VERSION=1.0.0
      - ENVIRONMENT=production
    depends_on:
      - backend
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Backend API Gateway
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=kea
      - DB_USER=admin
      - DB_PASSWORD=admin
      - KEA_CA_URL=http://kea-ca:8000
      - KEA_CA_USER=admin
      - KEA_CA_PASSWORD=admin
    depends_on:
      - postgres
      - kea-ca
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=kea
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./config/database/dns-schema.sql:/docker-entrypoint-initdb.d/01-dns-schema.sql
      - ./config/database/users-schema.sql:/docker-entrypoint-initdb.d/02-users-schema.sql
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sagaos"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Kea Control Agent
  kea-ca:
    image: sagaos/kea:latest  # Replace with actual Kea image
    ports:
      - "8000:8000"
    volumes:
      - kea_config:/etc/kea
      - kea_data:/var/lib/kea
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3

  # BIND DNS Server (optional)
  bind:
    image: internetsystemsconsortium/bind9:9.18
    ports:
      - "53:53/udp"
      - "53:53/tcp"
      - "953:953/tcp"  # rndc
    volumes:
      - bind_config:/etc/bind
      - bind_data:/var/lib/bind
    restart: unless-stopped

volumes:
  postgres_data:
  kea_config:
  kea_data:
  bind_config:
  bind_data:

networks:
  default:
    name: sagaos-network
